name: Build and deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Ensure this matches your project's requirement
          include-prerelease: true

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build ASP.NET Core Project
      - name: Build with dotnet
        run: dotnet build ./AspNetCore/XKSoft_ServiceDesk_DemoAPI/XKSoft_ServiceDesk_DemoAPI.csproj --configuration Release

      # Publish ASP.NET Core Project
      - name: dotnet publish
        run: dotnet publish ./AspNetCore/XKSoft_ServiceDesk_DemoAPI/XKSoft_ServiceDesk_DemoAPI.csproj -c Release -o ${{runner.temp}}/myapp

      # Upload ASP.NET Core artifact for deployment
      - name: Upload ASP.NET artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{runner.temp}}/myapp

      # Deploy ASP.NET Core to Azure Web App
      - name: Deploy ASP.NET Core to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'xksoft-servicedesk-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{runner.temp}}/myapp

      # Prepare Classic ASP files for deployment
      - name: Prepare Classic ASP files
        run: |
          mkdir ${{runner.temp}}/classicasp
          cp -r ./ClassicASP/* ${{runner.temp}}/classicasp/

      # Upload Classic ASP artifact for deployment
      - name: Upload Classic ASP artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: classic-asp
          path: ${{runner.temp}}/classicasp

      # Deploy Classic ASP to Azure Web App
      - name: Deploy Classic ASP to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'XKSoft-ServiceDesk'  # Make sure to have a separate web app or appropriate routing for Classic ASP
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_CLASSICASP }}
          package: ${{runner.temp}}/classicasp
