name: Build and Deploy ASP.NET Core to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Ensure this matches your project's requirement
          include-prerelease: true

      - name: Build ASP.NET Core Project
        run: |
          dotnet build ./AspNetCore/XKSoft_ServiceDesk_DemoAPI/XKSoft_ServiceDesk_DemoAPI.csproj --configuration Release

      - name: Publish ASP.NET Core Project
        run: |
          dotnet publish ./AspNetCore/XKSoft_ServiceDesk_DemoAPI/XKSoft_ServiceDesk_DemoAPI.csproj -c Release -o ${{runner.temp}}/myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ASP.NET Core to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'xksoft-servicedesk-api'
          package: ${{runner.temp}}/myapp
