name: Build and deploy ASP.Net Core app to Azure Web App - XKSoft-ServiceDesk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Specify exact prerelease version if necessary
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish  # Changed to a more typical directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./publish  # Ensure this matches the output of dotnet publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  # Verify this output is correct

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_10ABB38248794EB48E8CFC2EC269F500 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1E096AC5315944D8A57030E94B60457D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3C02EDBE17F44B23B7833DE701B56724 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'XKSoft-ServiceDesk'
          slot-name: 'Production'
          package: ./publish  # Specify the exact path if needed
