name: Build and deploy to Azure Web App and Container Instance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Ensure this matches your project's requirement
          include-prerelease: true

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build and Publish ASP.NET Core Project
      - name: Build and Publish ASP.NET Core
        run: |
          dotnet build ./AspNetCore/XKSoft_ServiceDesk_DemoAPI/XKSoft_ServiceDesk_DemoAPI.csproj --configuration Release
          dotnet publish ./AspNetCore/XKSoft_ServiceDesk_DemoAPI/XKSoft_ServiceDesk_DemoAPI.csproj -c Release -o ${{runner.temp}}/myapp

      # Deploy ASP.NET Core to Azure Web App
      - name: Deploy ASP.NET Core to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'xksoft-servicedesk-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{runner.temp}}/myapp

      # Build Docker Image and Push to ACR
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/xksoftservicedesk:latest -f Dockerfile .
          docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/xksoftservicedesk:latest

      # Deploy to Azure Container Instance
      - name: Deploy to Azure Container Instance
        run: |
          az container create --resource-group XKSoft_ServiceDesk_Resources \
            --name xksoftservicedesk-container \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/xksoftservicedesk:latest \
            --cpu 1 --memory 1.5 \
            --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
            --dns-name-label xksoftservicedesk-unique-label \
            --ports 80 443
