name: Build, Push and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # Setup .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      # Build and Publish ASP.NET Core Project
      - name: Build and Publish ASP.NET Core
        run: |
          dotnet build ./AspNetCore/XKSoft_ServiceDesk_DemoAPI/XKSoft_ServiceDesk_DemoAPI.csproj --configuration Release
          dotnet publish ./AspNetCore/XKSoft_ServiceDesk_DemoAPI/XKSoft_ServiceDesk_DemoAPI.csproj -c Release -o ${{runner.temp}}/myapp

      # Docker Login to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yourusername/yourrepo:latest

      # Deploy to Azure Container Instance
      - name: Deploy to Azure Container Instance
        run: |
          az container create --resource-group XKSoft_ServiceDesk_Resources \
            --name xksoftservicedesk-container \
            --image docker.io/yourusername/yourrepo:latest \
            --cpu 1 --memory 1.5 \
            --registry-login-server docker.io \
            --registry-username ${{ secrets.DOCKER_USERNAME }} \
            --registry-password ${{ secrets.DOCKER_PASSWORD }} \
            --dns-name-label xksoftservicedesk-unique-label \
            --ports 80 443
